name: Deploy

on:
  push:
    branches: [main]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Deno environment
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Verify formatting
        run: deno fmt -c deno.json --check

      - name: Run linter
        run: deno lint -c deno.json

  deploy:
    needs: test

    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Setup Deno environment
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Setup Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.deno
            ~/.cache/deno
            _cache
          key: ${{ runner.os }}-deno-${{ hashFiles('**/_config.ts', '**/import_map.json') }}

      - name: Build site
        run: deno task build

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "lume"
          import-map: "./import_map.json"
          entrypoint: "./serve.ts"
